### ISSUE TITLE
Style your website

### ISSUE THREAD

**Issue by JamieKaiRemkes** [NaomiJoanne/potential-potato#4]
As an upcoming design queen it's expected that your website looks and feels great. Might be handy to add some cascading style sheets to the document for easy styling!

Helpful links:
- [CSS](https://www.w3schools.com/html/html_css.asp)
- [web.dev](https://web.dev/learn/css/?gclid=Cj0KCQjwheyUBhD-ARIsAHJNM-P0yFcx8xGSHG0DHBehd38-ME8KxhqneELxLyFOHpD1D0IZW1tTuggaApLoEALw_wcB)
- [design](https://www.figma.com/file/VoI0jJEj52LZBMd6MBhKye)

**Comment by JamieKaiRemkes** [comment]
```css
@import url('https://fonts.googleapis.com/css?family=Quicksand&display=swap');
body {
  font-family: 'Muli', sans-serif;
  color: rgba(0, 0, 0, 0.8);
  font-weight: 400;
  line-height: 1.58;
  letter-spacing: -.003em;
  font-size: 20px;
  padding: 70px;
}
```
